// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";
import path from "path";

// Load .env.local first (higher priority), then .env
config({ path: ".env.local" });
config({ path: ".env" });

// Use absolute paths to prevent nested folder creation
const projectRoot = process.cwd();

export default defineConfig({
  schema: path.join(projectRoot, "prisma", "schema.prisma"),
  migrations: {
    path: path.join(projectRoot, "prisma", "migrations"),
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
